language: java
jdk:
- openjdk8
sudo: false
script: mvn clean deploy
env:
  global:
  - SONATYPE_USERNAME=mihxil
  - secure: F5owiSa+rEHU/grDD9lbOQchCLZubtT9hvZPZc0CVkiM8Kqf98fBqmaDgsNi7Orlb5gPh6tLbAoIPNKWERugoyR+w/y9oBjLeQWzyz12paqXM2gQ+0w52f26x6aZ3Mt07NgIPRAIX2PiNG/YJ6Z/QT4sw+rNV3JDqMjSYkok+zrsi3yjm/5XV5ZHExr5Nu5CKO0I8VRZlnUkEji/GtpievAns91wfSTAWpoNRuw8fvgTBRxIMk8nKBmbVO/tVag8a+cNHKvpPQ99ZgLMSIW/xyoy1fvLx/XoksID+G/RMqwktaaZUzJI2t1MTjYf3fAxLsYYi3bhwS1IesNVpZe7jiDWlV6P67gEhUns9i4bzsb5Y82y15fRy1MpUjmaTcff/pNMowqMHHnKWjrSa6evFTLy9jcTSmExrqytdSLrk9f5PnlNlqnSgKczYwiEINSvJOre9cRRzaBxfLqO2fRi2UGB01SaNrcEVGJrTd8HYU6t7y5ZwzO7PvzaXiEq/4SNdyi7CRf/5L+Ni7mtqVGfDTEeIutU4GtX5jMJXnY9DtLi5XBvGKWahun6OK0iK4gAgST9ab2DLTbzVVlpOHt8TP7BdZrVgepAYwM6EkmULcdfdQ77LqqQYs6XJc4NvUaQr9Q4ZAf7POuXFMTzDDJ/ppdMexpzIHKF688iQQtE400=
