language: java
jdk:
- openjdk8
sudo: false
env:
  global:
    - SONATYPE_USERNAME=mihxil
    - secure: mhoba2GWdMQ3lJo7nhL0+6GwFhv4oKvhmeq2LpARUpUxdPEkdhTQ/jjsNTg9ebdmO+DbAiE/izHHdKDNUxztREdasvztg7UtTNoIqloyxZI9tEbpOC/0SzXW3l+vM2/6FpIQ//EeXBpMj/pMJSo1KvGgcN5Pdk5BUXK9d4Maxr2wnD9HuRnI1tYaWy1a8bjtyR3h/gtHtWD0wHrjIlsDS8rGCnctATUq0uCblmCBaTwbUKmRyvO8H4FXGSDduJtB/ogl+vkisjumHX5tLPNMpFUsW8K7idxG1r7BaDeCKGarEx/7fpQ/7Yd0w0TNGSqT1SmHiUTnaoVVoy/xUtyIZ6dHPV4wYf1a1AGRP6x2DKmkRbMN15yB6pIpUdo75AaNb2eHkkMOr/Xif6J34oArlxNZysbqMuwTymEYISVY0RNsqM+NLar8IGR/RXNpLPn4laad95wa5SFRS7qx8wO8ISat21tY+/qJQNs1D1lXqQDafzN6HHKXe46dbou/YRlqjoj9g6sXRNPb4ZNDQHGT3rFRi7WAy1SS3MmHnzeGG2cj9fqvcV1SOtbdBzJSWZ8KRhHIAk0TJ/x2PoNYLdmhTO45fX9/mG+QZphqcSzj8H6SlIezxZa6KFe5R5LKP1LhWeoE/KOWgNNc9Fm1lNVmmm5ZToy4m8UAemIr4RwLY/w=
