= svg-objects
:toc:
:version: 0.4-SNAPSHOT


image:https://img.shields.io/maven-central/v/org.meeuw/svg-objects.svg?label=Maven%20Central[Maven Central,link=https://search.maven.org/search?q=g:%22org.meeuw%22%20AND%20a:%22svg-objects%22]
image:https://github.com/mihxil/svg-objects/workflows/build/badge.svg?[Build Status,link=https://github.com/mihxil/svg-objects/actions?query=workflow%3Abuild]

Provides some simple parameterized SVG objects.


This can be used in a simple servlet environment or spring boot.

Each response is served with `Content-Type: image/svg+xml` and `Cache-Control: max-age=3600`.


== Servlets with jspx

Take a dependency like so:

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.meeuw</groupId>
  <artifactId>svg-objects</artifactId>
  <version>{version}</version>
</dependency>
----

The name of the web-fragment is 'svgobjects', which you may want to include in `web.xml/absolute-ordering` if your web.xml is metadata-complete.


If you use the spinner it currently requires JSTL too
[source, xml]
----
<dependency>
  <groupId>org.glassfish.web</groupId>
  <artifactId>jakarta.servlet.jsp.jstl</artifactId>
  <version>3.0.1</version>
</dependency>
----
The dependency is not transitive, you may not need it at all (if not using spinner), or you may want javax version (javax.servlet.jsp.jstl) if you are on an older servlet container.


== spring boot

[source,xml,subs="attributes+"]
----
<dependency>
  <groupId>org.meeuw</groupId>
  <artifactId>svg-objects-spring-boot</artifactId>
  <version>{version}</version>
</dependency>
----

See link:demo/README.adoc[demo] for a runnable example.


== /meeuw/spinner

A parameterized SVG spinner


Use:
[source,jsp]

.usage in HTML (jsp actually)
----
<img src="${pageContext.request.contextPath}/meeuw/spinner?size=10"
  height="10" width="10" />
----
[cols="1,1"]
|===
| param | default

| `size`
| `64`

| `color`
| `#000`

| `circles`
| `7`

| `steps`
| `50`

| `dur`
| `1500ms`
|===

And the default then renders like so:
image:spinner.svg[]


== `/meeuw/polygon`

Use: `${pageContext.request.contextPath}/meeuw/polygon?&lt;params&gt;`


[cols="1,1"]
|===
| param | default

| `size`
| `16`

| `color`
| `#000`

| `sides`
| `3`
|===



== /meeuw/circle

Use: `${pageContext.request.contextPath}/meeuw/circle?&lt;params&gt;`


[cols="1,1"]
|===
| param | default

| `size`
| `16`

| `color`
| `#000`
|===


